### ISSUE TITLE
Activation function

### ISSUE THREAD

**Issue by markNZed** [AP6YC/AdaptiveResonance.jl#16]
I'm trying to understand this code and learn Julia and learn ART. So this may well be a stupid question. 

In the choice function of the 1991 Fuzzy ART paper the denominator includes the norm of the weights for the current category. In the code it seems like the norm of the first category is always taken for the denominator. 

https://github.com/AP6YC/AdaptiveResonance.jl/blob/692d59fa5ce6a423fe12a9fbfd2f60919f8aabe7/src/ART/DVFA.jl#L363

In the 2018 paper on DVFA this does not seem to be mentioned so I was assuming it should be the same as Fuzzy ART. Is this something specific about the DVFA implementation?  Or, more likely, my misunderstanding.

**Comment by AP6YC** [comment]
This is not a stupid question at all. You are absolutely correct that the denominator norm should be the L1 norm of the current category, so this is actually a very stupid bug that you caught 😊
![image](https://user-images.githubusercontent.com/17498866/134696569-31f2e42c-aa23-4279-9d6e-c96b9926f834.png)
Making the changes now!

**Comment by AP6YC** [comment]
Because I haven't initiated a GitFlow or feature-based workflow for this repo yet to have a pull request, this issue is fixed by this commit:
https://github.com/AP6YC/AdaptiveResonance.jl/commit/490e30008f60fed01d4d2f2931adef77692246fe
