### ISSUE TITLE
How should users contribute/ask questions?

### ISSUE THREAD

**Issue by aaronpeikert** [AP6YC/AdaptiveResonance.jl#18]
Hey @AP6YC you really invested a lot of time into making this a usable package! However, when you get some users they will inevitably have some questions.

Maybe you want to point users to where they should ask them (e.g. via issues, StackOverflow or mail).

A Code of Conduct would also be a nice addition:
https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-code-of-conduct-to-your-project

I personally like the [Berlin CoC](https://berlincodeofconduct.org).

Related: https://github.com/openjournals/joss-reviews/issues/3671

**Comment by aaronpeikert** [comment]
GitHub issues might be the best thing for you.
Mentioning them as a place to ask questions and report bugs in Readme and Docs is certainly enough.

Some packages also have this in their startupmessage:

> AdaptiveResonance.jl is beta software. Feel free to ask questions and report bugs at https://github.com/AP6YC/AdaptiveResonance.jl/issues

**Comment by hayesall** [comment]
Some additional feedback on this topic:

The `README / Contributing` section currently reads: "Please raise an issue." It looks like there are some links hidden in the README markdown source such as 

```markdown
[contrib-url]: https://juliadocs.github.io/Documenter.jl/dev/contributing/
```

... these might be removed or updated to point to AdaptiveResonance links.

---

Please address each of these in the README (and perhaps on a Developer Notes page #22):

1) **Contribute to the software** --- Do you accept pull requests? Docs, fixes, etc.?
2) **Report issues or problems with the software** --- Issues are good.
3) **Seek support** --- Do you prefer an email or an issue? (e.g. we prefer filing public issues so others can learn or contribute, but questions over email are fine too).

**Comment by AP6YC** [comment]
@hayesall Thanks for the catch! PR #37 fixes that boilerplate link in the README, while PR #36 moves and slightly expands upon the contributing section in the README.

Also, PR #35 fleshes out the developer notes in the contributing page. I realized that I didn't address your three bullet points for the README, so I'll address them in one last PR and close this issue.
