### ISSUE TITLE
[paper] Statement of need - Target audience

### ISSUE THREAD

**Issue by hayesall** [AP6YC/AdaptiveResonance.jl#24]
Who is this package for?

- The wider ML community
- the Julia community
- people who are working on ART algorithms who may want benchmarks to compare against?

**Comment by aaronpeikert** [comment]
I think this single issue provides the greatest potential for improving the paper.

If this is for the ML community in Julia the paper should include some problems one can solve with ART.
However, if it is for the ART folks the current paper reads a bit like YAART (**Y**et **A**nother **ART** package) but in my experience, an implementation in Julia has great benefits beyond just being an implementation in another programming language, e.g. julia packages are easier to extend, may benefit from cutting edge numerical computing (GPU/TPU, sparse arrays, symbolic computation etc.) that are not easily available elsewhere, etc.

**Comment by AP6YC** [comment]
PR #46: I updated the paper to include a target audience section that addresses your feedback. To tackle the types-of-problems idea, I wrote up a simplified summary of ART theory and algorithm basics to explain what ART is and what it is used for.

**Comment by AP6YC** [comment]
I'll close this issue for now. If you guys find anything is unclear or lacking, I will gladly write up more 😊
