### ISSUE TITLE
[paper] State of the field

### ISSUE THREAD

**Issue by hayesall** [AP6YC/AdaptiveResonance.jl#25]
The "Tutorial / Guide" documentation page already contains some discussion which could be worth mentioning in the paper.

- For example: supervised vs. unsupervised, batch vs. incremental mode.
- What are the motivations for designing the package with these features?

**Comment by AP6YC** [comment]
Good suggestions! I'll update the paper with a section reflecting exactly those bullet points.

**Comment by AP6YC** [comment]
I implemented your notes about adding some discussion about the package implementation in Feature #52.

I added an implementation section that summarizes from the docs the supervised vs. unsupervised, batch vs. incremental, training vs. inference, and match vs. mismatch. I made these sections as high-level as possible to avoid deprecating the paper in the future while still providing the reader a better understanding of the structure and objectives of the package.

As with the other issues, I will close this for now and reopen if you'd like to see something different 😊.
