### ISSUE TITLE
[documentation] What is the 'Hello World' for this code?

### ISSUE THREAD

**Issue by hayesall** [AP6YC/AdaptiveResonance.jl#26]
What is a *minimal working example for a new user (who may not already be an expert in Adaptive Resonance Theory)?*

One entry point might be structured like: '*Assuming you know a little about machine learning already, here is how we can setup a supervised/unsupervised problem in this new setting*':

---

Here's a simple example with two overlapping multivariate Gaussians:

![Four plots demonstrating the ART algorithms. From left to right, original data, unsupervised DDVFA, supervised DDVFA, and Supervised SFAM.](https://user-images.githubusercontent.com/11916674/136672487-e580ee67-4ecb-467e-83f9-ecaed3277386.png)

And here is the code to produce the figure, feel free to use this:

```julia
# Copyright © 2021 Alexander L. Hayes
# MIT License

using AdaptiveResonance
using Distributions, Random
using MLDataUtils
using Plots

"""
Demonstrates Unsupervised DDVFA, Supervised DDVFA, and (Supervised) SFAM on a toy problem
with two multivariate Gaussians.
"""

# Setup two multivariate Gaussians and sampling 1000 points from each.

rng = MersenneTwister(1234)
dist1 = MvNormal([0.0, 6.0], [1.0 0.0; 0.0 1.0])
dist2 = MvNormal([4.5, 6.0], [2.0 -1.5; -1.5 2.0])

N_POINTS = 1000

X = hcat(rand(rng, dist1, N_POINTS), rand(rng, dist2, N_POINTS))
y = vcat(ones(Int64, N_POINTS), zeros(Int64, N_POINTS))

p1 = scatter(X[1,:], X[2,:], group=y, title="Original Data")

(X_train, y_train), (X_test, y_test) = stratifiedobs((X, y))

# Unsupervised DDVFA
art = DDVFA()
train!(art, X_train)
y_hat_test = AdaptiveResonance.classify(art, X_test)
p2 = scatter(X_test[1,:], X_test[2,:], group=y_hat_test, title="Unsupervised DDVFA")

# Supervised DDVFA
art = DDVFA()
train!(art, X_train, y=y_train)
y_hat_test = AdaptiveResonance.classify(art, X_test)
p3 = scatter(X_test[1,:], X_test[2,:], group=y_hat_test, title="Supervised DDVFA", xlabel="Performance: " * string(round(performance(y_hat_test, y_test); digits=3)))

# Supervised SFAM
art = SFAM()
train!(art, X_train, y_train)
y_hat_test = AdaptiveResonance.classify(art, X_test)
p4 = scatter(X_test[1,:], X_test[2,:], group=y_hat_test, title="Supervised SFAM", xlabel="Performance: " * string(round(performance(y_hat_test, y_test); digits=3)))

# Performance Measure + display the plots
plot(p1, p2, p3, p4, layout=(1, 4), legend = false, xtickfontsize=6, xguidefontsize=8, titlefont=font(8))
```

**Comment by AP6YC** [comment]
Thanks for writing this up! I really like the idea of a small example with figures to show off and bootstrap code for someone unfamiliar with ART. I think that I'd like to take you up on your offer and add it to the docs.

**Comment by AP6YC** [comment]
Thank you for mentioning those packages; I actually really like DemoCards, and it seems to use Literate under the hood to an extent. I think that that would cleanly organize the example page. I'll link the feature PR when I've got something to show for your approval.

**Comment by AP6YC** [comment]
PR #39 implemented the basic example page from a modification of your code above, but a separate upcoming PR will add the DemoCards examples.

**Comment by AP6YC** [comment]
PR #49 implements the promised DemoCards examples. Thanks again for the recommendations! There was a little bit of a learning curve and debugging on the CI end, but I've added proper DemoCards notebooks for each example using MLDatasets and MLDataUtils (inspired by your working example above).
