### ISSUE TITLE
[documentation] DataConfig parameters / Index

### ISSUE THREAD

**Issue by hayesall** [AP6YC/AdaptiveResonance.jl#28]
The Index is a little hit-or-miss for me currently. It's useful as a big list of the types and methods, but it's sparse on documentation for what function attributes mean.

---

- At a minimum, I'd like to see functions and types from the [Examples](https://ap6yc.github.io/AdaptiveResonance.jl/dev/man/examples/) to have fairly complete docstrings.
- The [Guide / ART Options](https://ap6yc.github.io/AdaptiveResonance.jl/dev/man/guide/#art_options) are pretty good, some of these would make sense as part of the docstrings for the `opts` objects.

**Comment by AP6YC** [comment]
PR #56 finally addresses some of your index concerns.

In that feature PR, I reorganized the full index page, included only exported names, and significantly expanded the docstrings to be more helpful and accessible. More plainly, I documented the keyword parameters in each options struct, the working parameters of the modules themselves, and added doc links and citations where relevant. One of the trickier bits was the overloaded `train!` and `classify` methods; there are four `train!`s (ART vs. ARTMAP, incremental vs. batch) and two `classify`s (incremental vs. batch, same for ART and ARTMAP).

I'll keep thinking on how to better organize the index, such as consolidating the overloaded method definitions in a way that makes sense. Furthermore, I'd like to organize the index list into ART modules and options, ARTMAP modules and options, etc., but I will leave the `Documenter.jl` wrangling for a future PR. In the meantime, I hope that the new index is more to your satisfaction. Thanks again for all of your feedback and help!
