### ISSUE TITLE
Warning of method definition

### ISSUE THREAD

**Issue by markNZed** [AP6YC/AdaptiveResonance.jl#41]
I'm using Julia 1.6.3 and see warnings like:
```
      From worker 2:	WARNING: Method definition (::Type{AdaptiveResonance.FAM})() in module AdaptiveResonance at /Users/XXX/AdaptiveResonance.jl/src/ARTMAP/FAM.jl:82 overwritten at /Users/XXX/AdaptiveResonance.jl/src/ARTMAP/FAM.jl:64.
      From worker 2:	  ** incremental compilation may be fatally broken for this module **
```
It does not seem to break things but it would be nice if we did not have these warnings.

**Comment by AP6YC** [comment]
Good catch! I was hoping to fold in a lot of overlapping fixes with broader changes in a major release, so that is why things have stayed in `develop`.  I'll post an update here when that release is merged.

**Comment by AP6YC** [comment]
PR #48 pulls all of the recent changes into the master, including a fix to this method definition issue. I have forgone from waiting for a major release to be able to address this issue and get other upcoming changes into master.
